---
version: 1.0.0
recipes:
- link: docs/Getting-Started/Getting-Started-General.md
  title: Payment with JS
- link: docs/useCases/DepositAccountOrigination.md
  title: Payment with Py
- link: docs/useCases/CustomerMaintenance.md
  title: Payment with Rust
- link: docs/fintechs/accountholder.md
  title: Payment with Java
